version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: smart_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: smart_inventory_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: smart_inventory_app
    restart: always
    depends_on:
      - mysql
    ports:
      - "9194:9194"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/smart_inventory_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

volumes:
  mysql_data: